Repository pt4team2/coworkers, pull requests merged in 2024-09, with the labels that each got.

#3 Feat: 헤더 퍼블리싱
  .eslintrc.json
  package.json
  src/app/(routes)/home/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/assets/icons/ic-menu.svg
  src/assets/icons/ic_kebab.svg
  src/assets/icons/ic_plus.svg
  src/assets/icons/ic_profile.svg
  src/assets/icons/ic_toggleDown.svg
  src/assets/images/img_logo.svg
  src/assets/images/img_todo.svg
  src/components/header/Header.tsx
  src/components/header/Profile.tsx
  src/components/header/Team.tsx
  src/components/header/TeamDropdown.tsx
  src/components/header/mockData.ts
  src/styles/globals.css
Labels: ⭐️Feature

#6 feat: 팀 페이지 퍼블리싱
  package-lock.json
  package.json
  src/app/(routes)/teampage/page.tsx
  src/assets/icons/ic_done.svg
  src/assets/icons/ic_setting.svg
  src/assets/images/img_done.svg
  src/assets/images/img_memberProfile.svg
  src/assets/images/img_teambg.svg
  src/components/header/Profile.tsx
  src/components/header/TeamDropdown.tsx
  src/components/header/mockData.ts
  src/components/pages/teampage/memberList/MemberCard.tsx
  src/components/pages/teampage/memberList/MemberList.tsx
  src/components/pages/teampage/taskList/ProgressBar.tsx
  src/components/pages/teampage/taskList/Task.tsx
  src/components/pages/teampage/taskList/TasksList.tsx
  src/components/pages/teampage/taskReport/ProgressBar.tsx
  src/components/pages/teampage/taskReport/ProgressBarMobile.tsx
  src/components/pages/teampage/taskReport/TaskReport.tsx
  src/components/pages/teampage/teamSetting/TeamSetting.tsx
  src/data/groupData.ts
  src/data/mockData.ts
  src/styles/themes/colors.css
  src/types/.gitignore
  src/types/Group.ts
  src/types/Task.ts
  tailwind.config.ts
Labels: ⭐️Feature, 👏🏼 done

#8 refactor: 로그인 페이지 코드 리팩토링
  src/app/(routes)/login/page.tsx
  src/app/(routes)/resetPassword/page.tsx
  src/app/(routes)/signup/page.tsx
  src/components/auth/FormField.tsx
  src/hooks/useFormFieldData.tsx
  src/utils/schema.tsx
Labels: 👏🏼 done

#10 refactor: 비밀번호 재설정 페이지 코드 리팩토링
  src/app/(routes)/resetPassword/page.tsx
  src/app/page.tsx
  src/hooks/useFormFieldData.tsx
  src/types/auth.ts
  tailwind.config.ts
Labels: 👏🏼 done

#13 feat: NextAuth를 이용한 로그인 기능 구현
  .env
  package-lock.json
  package.json
  src/app/(routes)/login/page.tsx
  src/app/(routes)/resetPassword/page.tsx
  src/app/(routes)/signup/page.tsx
  src/app/api/auth/[...nextauth]/route.ts
  src/app/api/auth/axiosInstance.ts
  src/app/layout.tsx
  src/components/auth/FormField.tsx
  src/components/auth/Providers.tsx
  src/components/header/Profile.tsx
  src/hooks/formFieldData.tsx
  src/middleware.ts
  src/store/formStore.tsx
  src/store/loginStore.tsx
  src/types/auth.ts
  src/types/next-auth.d.ts
  tailwind.config.ts
Labels: ⭐️Feature, 👏🏼 done

#12 feat: API 연동 및 NextAuth를 이용하여 회원가입 및 자동로그인 기능 구현 + 간편 로그인 추가(0917)
  src/app/(routes)/login/page.tsx
  src/app/(routes)/reset-password/page.tsx
  src/app/(routes)/signup/page.tsx
  src/app/api/auth/[...nextauth]/route.ts
  src/app/layout.tsx
  src/assets/icons/close.svg
  src/assets/icons/error.svg
  src/assets/icons/info.svg
  src/assets/icons/success.svg
  src/components/auth/FormField.tsx
  src/components/auth/OAuthLogin.tsx
  src/components/modal/Modal.tsx
  src/components/modal/ModalWrapper.tsx
  src/components/toast/Toast.tsx
  src/store/useModalStore.tsx
  src/store/useToastStore.tsx
  src/types/auth.ts
  src/types/modal.ts
  src/types/next-auth.d.ts
  src/types/toast.ts
  src/utils/schema.tsx
  tailwind.config.ts
Labels: ⭐️Feature, 👏🏼 done

#17 feat: 데이터 페칭 훅 추가 및 헤더 드롭다운 추가
  src/app/(routes)/layout.tsx
  src/app/(routes)/teampage/[groupId]/page.tsx
  src/app/(routes)/teampage/[id]/page.tsx
  src/app/api/auth/axiosInstance.ts
  src/app/layout.tsx
  src/components/header/Header.tsx
  src/components/header/Profile.tsx
  src/components/header/ProfileDropdown.tsx
  src/components/header/TeamDropdown.tsx
  src/components/pages/teampage/memberList/MemberList.tsx
  src/components/pages/teampage/taskList/Task.tsx
  src/components/pages/teampage/taskList/TasksList.tsx
  src/components/pages/teampage/teamSetting/TeamSetting.tsx
  src/hooks/useGroup.tsx
  src/hooks/useMemberships.tsx
  src/hooks/useTaskList.tsx
  src/hooks/useTasks.tsx
  src/hooks/useUser.tsx
  src/styles/globals.css
  src/types/.gitignore
  src/types/Group.ts
  src/types/user.ts
Labels: 🥲미완성
